# type: ignore
"""initial schema

Revision ID: a9cf6c214996
Revises: 
Create Date: 2026-07-19 10:26:21.761325

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'a9cf6c214996'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('repository_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('default_branch', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('project_type', sa.Enum('web', 'unity', 'desktop', 'backend', 'other', name='projecttype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_type'), ['project_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=True)

    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('operating_system', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sa.Enum('online', 'offline', 'degraded', 'unknown', name='workerstatus'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('claude_available', sa.Boolean(), nullable=False),
    sa.Column('codex_available', sa.Boolean(), nullable=False),
    sa.Column('unity_available', sa.Boolean(), nullable=False),
    sa.Column('unity_mcp_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workers_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workers_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_workers_status'), ['status'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('agent_type', sa.Enum('claude', 'codex', name='agenttype'), nullable=True),
    sa.Column('status', sa.Enum('queued', 'starting', 'running', 'waiting_for_user', 'waiting_for_approval', 'testing', 'needs_review', 'completed', 'blocked', 'failed', 'cancelled', 'rejected', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'critical', name='taskpriority'), nullable=False),
    sa.Column('discord_guild_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('discord_channel_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('discord_thread_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('requested_by', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('working_directory', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('worktree_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('start_commit', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('end_commit', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('result_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tests_status', sa.Enum('pending', 'running', 'passed', 'failed', 'not_run', name='checkstatus'), nullable=False),
    sa.Column('build_status', sa.Enum('pending', 'running', 'passed', 'failed', 'not_run', name='checkstatus'), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_agent_type'), ['agent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_last_activity_at'), ['last_activity_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tasks_requested_by'), ['requested_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_worker_id'), ['worker_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.Enum('log', 'screenshot', 'test_report', 'build', 'diff', 'patch', 'document', 'other', name='artifacttype'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('local_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_artifact_type'), ['artifact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_task_id'), ['task_id'], unique=False)

    op.create_table('task_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_events_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_events_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_task_events_created_at'))

    op.drop_table('task_events')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_task_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_artifact_type'))

    op.drop_table('artifacts')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_worker_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_requested_by'))
        batch_op.drop_index(batch_op.f('ix_tasks_public_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_tasks_last_activity_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_is_archived'))
        batch_op.drop_index(batch_op.f('ix_tasks_created_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_agent_type'))

    op.drop_table('tasks')
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workers_status'))
        batch_op.drop_index(batch_op.f('ix_workers_name'))
        batch_op.drop_index(batch_op.f('ix_workers_last_seen_at'))

    op.drop_table('workers')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_slug'))
        batch_op.drop_index(batch_op.f('ix_projects_project_type'))
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.drop_index(batch_op.f('ix_projects_is_active'))

    op.drop_table('projects')
    # ### end Alembic commands ###
