# Build a clean, shareable copy of Agent Hub — source only, none of this PC's
# personal data. What is left out:
#   * .env               (your config)
#   * openacp-config/    (your Discord bot token bundle)
#   * agent_hub.db       (your tasks/history)
#   * .venv, node_modules, .next, caches, .git, .claude  (regenerated by setup)
#
# The recipient runs install-agent-hub-prerequisites.bat, and setup recreates
# everything from source. They supply their OWN Discord bot — nothing of yours
# travels in the zip.
#
# Usage:
#   pwsh -File .\scripts\make-distributable.ps1                 # -> Desktop\agent-hub.zip
#   pwsh -File .\scripts\make-distributable.ps1 -OutDir D:\out  # custom folder
#   pwsh -File .\scripts\make-distributable.ps1 -NoZip          # leave a folder, don't zip
param(
    [string]$OutDir = [Environment]::GetFolderPath("Desktop"),
    [switch]$NoZip
)
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot

$stageParent = Join-Path $env:TEMP "agent-hub-dist"
$stage = Join-Path $stageParent "agent-hub"

# Directories and files never included in a shared copy.
$excludeDirs = @(
    ".venv", "node_modules", ".next", "__pycache__", ".pytest_cache",
    "build", "*.egg-info", ".git", ".claude", "openacp-config"
)
$excludeFiles = @(
    ".env", "agent_hub.db", "agent_hub.db-journal", "agent_hub.db-wal",
    "agent_hub.db-shm", "*.pyc", "*.tsbuildinfo"
)

Write-Host "=== Building distributable copy ===" -ForegroundColor Cyan

if (Test-Path $stageParent) { Remove-Item -Recurse -Force $stageParent }
New-Item -ItemType Directory -Force -Path $stage | Out-Null

# /E all subfolders, /XD exclude dirs, /XF exclude files, quiet output.
robocopy $root $stage /E /XD $excludeDirs /XF $excludeFiles /NFL /NDL /NJH /NJS /NP | Out-Null
# robocopy uses bit-flag exit codes: 0-7 are success, 8+ are real failures.
if ($LASTEXITCODE -ge 8) { throw "robocopy failed with exit code $LASTEXITCODE" }
$global:LASTEXITCODE = 0

# A short, recipient-facing start guide.
$startHere = @"
Agent Hub - quick start (Windows 11)

1. Double-click   install-agent-hub-prerequisites.bat
   Installs Python, Node and PowerShell 7 if missing, then sets everything up
   (Python venv, npm packages, a fresh .env). Needs an internet connection.

2. Double-click   start-agent-hub.bat
   The dashboard opens at http://localhost:3000

3. In the dashboard open the "OpenACP" page and click "Install OpenACP".
   Then set up your OWN Discord bot token and workspace - see README.md
   (section "OpenACP channel bindings"). Nothing from the sender is included;
   you use your own Discord bot.

That's it.
"@
Set-Content -Path (Join-Path $stage "START-HERE.txt") -Value $startHere -Encoding UTF8

if ($NoZip) {
    Write-Host "`nClean copy ready (not zipped):" -ForegroundColor Green
    Write-Host "  $stage"
    return
}

if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Force -Path $OutDir | Out-Null }
$zip = Join-Path $OutDir "agent-hub.zip"
if (Test-Path $zip) { Remove-Item -Force $zip }

Compress-Archive -Path $stage -DestinationPath $zip
$sizeMb = [math]::Round((Get-Item $zip).Length / 1MB, 1)

Write-Host "`n=== Done ===" -ForegroundColor Green
Write-Host "  $zip  ($sizeMb MB)"
Write-Host "  Send this file. The recipient unzips it and double-clicks" -ForegroundColor Green
Write-Host "  install-agent-hub-prerequisites.bat." -ForegroundColor Green
