# Build a clean, shareable copy of Agent Deck — source only, none of this PC's
# personal data. What is left out:
#   * .env               (your config)
#   * openacp-config/    (your Discord bot token bundle)
#   * agent_deck.db       (your tasks/history)
#   * .venv, node_modules, .next, caches, .git, .claude  (regenerated by setup)
#
# The recipient runs install-agent-deck-prerequisites.bat, and setup recreates
# everything from source. They supply their OWN Discord bot — nothing of yours
# travels in the zip.
#
# Usage:
#   pwsh -File .\scripts\make-distributable.ps1                 # -> Desktop\agent-deck.zip
#   pwsh -File .\scripts\make-distributable.ps1 -OutDir D:\out  # custom folder
#   pwsh -File .\scripts\make-distributable.ps1 -NoZip          # leave a folder, don't zip
param(
    [string]$OutDir = [Environment]::GetFolderPath("Desktop"),
    [switch]$NoZip
)
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot

$stageParent = Join-Path $env:TEMP "agent-deck-dist"
$stage = Join-Path $stageParent "agent-deck"

# Directories and files never included in a shared copy.
$excludeDirs = @(
    ".venv", "node_modules", ".next", "__pycache__", ".pytest_cache",
    "build", "*.egg-info", ".git", ".claude", "openacp-config", "backup"
)
# Secrets are matched by pattern, not by exact name: ".env" alone does NOT
# match frontend\.env.local, which carries the write token just as plainly.
# ".env.*" is deliberately NOT used here - it would also drop .env.example,
# which the recipient needs. The assertion below is the real backstop.
$excludeFiles = @(
    ".env", "*.local", "*.bak", "*.bak-*",
    "agent_deck.db", "agent_deck.db-journal", "agent_deck.db-wal",
    "agent_deck.db-shm", "*.pyc", "*.tsbuildinfo"
)

Write-Host "=== Building distributable copy ===" -ForegroundColor Cyan

if (Test-Path $stageParent) { Remove-Item -Recurse -Force $stageParent }
New-Item -ItemType Directory -Force -Path $stage | Out-Null

# /E all subfolders, /XD exclude dirs, /XF exclude files, quiet output.
robocopy $root $stage /E /XD $excludeDirs /XF $excludeFiles /NFL /NDL /NJH /NJS /NP | Out-Null
# robocopy uses bit-flag exit codes: 0-7 are success, 8+ are real failures.
if ($LASTEXITCODE -ge 8) { throw "robocopy failed with exit code $LASTEXITCODE" }
$global:LASTEXITCODE = 0

# Backstop: refuse to ship anything that looks like a secret. An exclude list
# is easy to get subtly wrong (".env" not matching ".env.local" once shipped a
# live write token), so the staged tree is inspected rather than trusted.
$leaked = Get-ChildItem $stage -Recurse -Force -File | Where-Object {
    ($_.Name -like ".env*" -and $_.Name -ne ".env.example") -or
    $_.Name -like "*.local" -or $_.Name -like "*.bak*" -or
    $_.Name -like "*.db" -or $_.Name -eq "settings.json"
}
if ($leaked) {
    $list = ($leaked | ForEach-Object { $_.FullName.Substring($stage.Length + 1) }) -join "`n  "
    Remove-Item -Recurse -Force $stageParent
    throw "Refusing to build: these files would have shipped:`n  $list"
}
if (-not (Test-Path (Join-Path $stage ".env.example"))) {
    Remove-Item -Recurse -Force $stageParent
    throw "Refusing to build: .env.example is missing - the recipient needs it."
}

# A short, recipient-facing start guide.
$startHere = @"
Agent Deck - quick start (Windows 11)

1. Double-click   install-agent-deck-prerequisites.bat
   Installs Python, Node and PowerShell 7 if missing, then sets everything up
   (Python venv, npm packages, a fresh .env). Needs an internet connection.

2. Double-click   start-agent-deck.bat
   The dashboard opens at http://localhost:3000

3. In the dashboard open the "OpenACP" page and click "Install OpenACP".
   Then set up your OWN Discord bot token and workspace - see README.md
   (section "OpenACP channel bindings"). Nothing from the sender is included;
   you use your own Discord bot.

That's it.
"@
Set-Content -Path (Join-Path $stage "START-HERE.txt") -Value $startHere -Encoding UTF8

if ($NoZip) {
    Write-Host "`nClean copy ready (not zipped):" -ForegroundColor Green
    Write-Host "  $stage"
    return
}

if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Force -Path $OutDir | Out-Null }
$zip = Join-Path $OutDir "agent-deck.zip"
if (Test-Path $zip) { Remove-Item -Force $zip }

Compress-Archive -Path $stage -DestinationPath $zip
$sizeMb = [math]::Round((Get-Item $zip).Length / 1MB, 1)

Write-Host "`n=== Done ===" -ForegroundColor Green
Write-Host "  $zip  ($sizeMb MB)"
Write-Host "  Send this file. The recipient unzips it and double-clicks" -ForegroundColor Green
Write-Host "  install-agent-deck-prerequisites.bat." -ForegroundColor Green
